version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-django
    restart: always
    environment:
      POSTGRES_DB: doces_loja
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: